# Form implementation generated from reading ui file 'D:\!SubieProjects\businessThing\editUI.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(372, 419)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_name.setGeometry(QtCore.QRect(10, 0, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_dateIn = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_dateIn.setGeometry(QtCore.QRect(10, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_dateIn.setFont(font)
        self.lbl_dateIn.setObjectName("lbl_dateIn")
        self.date_in = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_in.setGeometry(QtCore.QRect(10, 70, 71, 22))
        self.date_in.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.date_in.setObjectName("date_in")
        self.lbl_timeIn = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_timeIn.setGeometry(QtCore.QRect(150, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_timeIn.setFont(font)
        self.lbl_timeIn.setObjectName("lbl_timeIn")
        self.time_in = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.time_in.setGeometry(QtCore.QRect(150, 70, 71, 22))
        self.time_in.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_in.setObjectName("time_in")
        self.time_out = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.time_out.setGeometry(QtCore.QRect(150, 130, 71, 22))
        self.time_out.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_out.setObjectName("time_out")
        self.lbl_timeOut = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_timeOut.setGeometry(QtCore.QRect(150, 110, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_timeOut.setFont(font)
        self.lbl_timeOut.setObjectName("lbl_timeOut")
        self.date_out = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_out.setGeometry(QtCore.QRect(10, 130, 71, 22))
        self.date_out.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.date_out.setObjectName("date_out")
        self.lbl_dateOut = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_dateOut.setGeometry(QtCore.QRect(10, 110, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_dateOut.setFont(font)
        self.lbl_dateOut.setObjectName("lbl_dateOut")
        self.btn_color = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_color.setGeometry(QtCore.QRect(10, 160, 121, 23))
        self.btn_color.setObjectName("btn_color")
        self.te_notes = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.te_notes.setGeometry(QtCore.QRect(10, 190, 351, 221))
        self.te_notes.setCursorWidth(1)
        self.te_notes.setObjectName("te_notes")
        self.btn_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(240, 160, 121, 23))
        self.btn_save.setObjectName("btn_save")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_name.setText(_translate("MainWindow", "Внесение записи"))
        self.lbl_dateIn.setText(_translate("MainWindow", "дата заезда"))
        self.date_in.setDisplayFormat(_translate("MainWindow", "dd.MM"))
        self.lbl_timeIn.setText(_translate("MainWindow", "время заезда"))
        self.lbl_timeOut.setText(_translate("MainWindow", "время выезда"))
        self.date_out.setDisplayFormat(_translate("MainWindow", "dd.MM"))
        self.lbl_dateOut.setText(_translate("MainWindow", "дата выезда"))
        self.btn_color.setText(_translate("MainWindow", "выбрать цвет "))
        self.te_notes.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.te_notes.setPlaceholderText(_translate("MainWindow", "заметки"))
        self.btn_save.setText(_translate("MainWindow", "сохранить"))
