# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 520)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tw_table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tw_table.setGeometry(QtCore.QRect(10, 10, 861, 441))
        self.tw_table.setObjectName("tw_table")
        self.tw_table.setColumnCount(0)
        self.tw_table.setRowCount(0)
        self.btn_notes = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_notes.setGeometry(QtCore.QRect(580, 460, 161, 31))
        self.btn_notes.setObjectName("btn_notes")
        self.btn_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(750, 460, 121, 31))
        self.btn_save.setObjectName("btn_save")
        self.btn_calendar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_calendar.setGeometry(QtCore.QRect(10, 460, 121, 31))
        self.btn_calendar.setObjectName("btn_calendar")
        self.btn_report = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_report.setGeometry(QtCore.QRect(140, 460, 121, 31))
        self.btn_report.setObjectName("btn_report")
        self.btn_additional = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_additional.setGeometry(QtCore.QRect(270, 460, 121, 31))
        self.btn_additional.setObjectName("btn_additional")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 21))
        self.menubar.setObjectName("menubar")
        self.m_file = QtWidgets.QMenu(parent=self.menubar)
        self.m_file.setObjectName("m_file")
        self.m_settings = QtWidgets.QMenu(parent=self.menubar)
        self.m_settings.setObjectName("m_settings")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.m_file.menuAction())
        self.menubar.addAction(self.m_settings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_notes.setText(_translate("MainWindow", "Внести заметки "))
        self.btn_save.setText(_translate("MainWindow", "сохранить"))
        self.btn_calendar.setText(_translate("MainWindow", "календарь"))
        self.btn_report.setText(_translate("MainWindow", "отчёт"))
        self.btn_additional.setText(_translate("MainWindow", "дополнительно"))
        self.m_file.setTitle(_translate("MainWindow", "файл"))
        self.m_settings.setTitle(_translate("MainWindow", "настройки"))
