# Form implementation generated from reading ui file 'D:\!SubieProjects\businessThing\reportDialogUI.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1033, 509)
        self.tw_reportTable = QtWidgets.QTableWidget(parent=Dialog)
        self.tw_reportTable.setGeometry(QtCore.QRect(10, 10, 1011, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_reportTable.sizePolicy().hasHeightForWidth())
        self.tw_reportTable.setSizePolicy(sizePolicy)
        self.tw_reportTable.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tw_reportTable.setObjectName("tw_reportTable")
        self.tw_reportTable.setColumnCount(0)
        self.tw_reportTable.setRowCount(0)
        self.btn_save = QtWidgets.QPushButton(parent=Dialog)
        self.btn_save.setGeometry(QtCore.QRect(900, 470, 121, 31))
        self.btn_save.setObjectName("btn_save")
        self.btn_close = QtWidgets.QPushButton(parent=Dialog)
        self.btn_close.setGeometry(QtCore.QRect(10, 470, 121, 31))
        self.btn_close.setObjectName("btn_close")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_save.setText(_translate("Dialog", "сохранить"))
        self.btn_close.setText(_translate("Dialog", "Закрыть"))
