# Form implementation generated from reading ui file '/Users/a.klivtsov/Desktop/CodieStuff/businessThing/mainUI.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 523)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tw_table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tw_table.setGeometry(QtCore.QRect(10, 10, 911, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_table.sizePolicy().hasHeightForWidth())
        self.tw_table.setSizePolicy(sizePolicy)
        self.tw_table.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tw_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tw_table.setObjectName("tw_table")
        self.tw_table.setColumnCount(0)
        self.tw_table.setRowCount(0)
        self.tw_table.horizontalHeader().setCascadingSectionResizes(True)
        self.tw_table.horizontalHeader().setStretchLastSection(False)
        self.tw_table.verticalHeader().setCascadingSectionResizes(True)
        self.tw_table.verticalHeader().setStretchLastSection(False)
        self.btn_notes = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_notes.setGeometry(QtCore.QRect(670, 460, 121, 31))
        self.btn_notes.setObjectName("btn_notes")
        self.btn_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(800, 460, 121, 31))
        self.btn_save.setObjectName("btn_save")
        self.btn_report = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_report.setGeometry(QtCore.QRect(10, 460, 121, 31))
        self.btn_report.setObjectName("btn_report")
        self.btn_del = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_del.setGeometry(QtCore.QRect(550, 460, 113, 31))
        self.btn_del.setObjectName("btn_del")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 24))
        self.menubar.setObjectName("menubar")
        self.m_file = QtWidgets.QMenu(parent=self.menubar)
        self.m_file.setObjectName("m_file")
        self.m_settings = QtWidgets.QMenu(parent=self.menubar)
        self.m_settings.setObjectName("m_settings")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.m_file.menuAction())
        self.menubar.addAction(self.m_settings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_notes.setText(_translate("MainWindow", "добавить"))
        self.btn_save.setText(_translate("MainWindow", "сохранить"))
        self.btn_report.setText(_translate("MainWindow", "отчёт"))
        self.btn_del.setText(_translate("MainWindow", "удалить"))
        self.m_file.setTitle(_translate("MainWindow", "файл"))
        self.m_settings.setTitle(_translate("MainWindow", "настройки"))
